services:
  postgis:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_DB=gpx
      - POSTGRES_USER=arbatov
      - POSTGRES_PASSWORD=12345
    ports:
      - 5432:5432
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@arbatov.me
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgis
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgis_data:
  pgadmin-data: